=head1 NAME 

tasksel - a user interface for installing tasks

=head1 SYNOPSIS

tasksel install <task>

tasksel [options]

=head1 DESCRIPTION

tasksel shows all available tasks and allows to user to select
ones to install

=head1 OPTIONS

=over 4

=item B<-t>

test mode; don't actually run apt-get on exit

=item B<-q>

queue installs; do not install packages with apt-get; just
queue them in dpkg

=item B<-r>

install all required-priority packages

=item B<-i>

install all important-priority packages

=item B<-s>

install all standard-priority packages

=item B<-n>

don't show UI; use with -r or -i usually

=item B<-a>

show all tasks, even those with no packages in them

=back

=head1 SEE ALSO

dpkg(8), apt-get(8)

=head1 FILES

F</usr/share/tasksel/debian-tasks.desc>
F</var/lib/dpkg/available>

=head1 AUTHOR

tasksel was written by Randolph Chung E<lt>tausq@debian.orgE<gt>.

=head1 HISTORY 

This document first appeared with tasksel-1.0
