#!/bin/sh
#
# Simple test script to automatically install/skip/mark/show tasks.
#
# To enable this test insert your tasks stanza a keyword like:
#
# Test-force: mark
#
case "$2" in
	install)
		exit 0 # do not display, but do install task
	;;
	skip)
		exit 1 # do not display task
	;;
	mark)
		exit 2 # display task, marked for installation
	;;
	show)
		exit 3 # display task, not marked for installation
	;;
	*)
		exit 1 # unknown value, skip the task
	;;
esac
